### ISSUE TITLE
1.18.2-1.19 version excludes 1.19

### ISSUE THREAD

**Issue by Lancelotbronner** [MrLoLf/InfinityFix#1]
I can't install the mod in 1.19 as it is excluded, is it a typo in the Modrinth page or the mod's manifest?

**Comment by MrLoLf** [comment]
I have had the wrong file uploaded, I am sorry for this, but it should be fixed now. Thanks for pointing out this issue.

**Comment by Lancelotbronner** [comment]
Thank you!
