### ISSUE TITLE
[Feature Request] Config

### ISSUE THREAD

**Issue by Roadhog360** [MrLoLf/InfinityFix#2]
I want the ability to disable mending and infinity being put together with this mod installed. I almost got this mod but realized it throws off the mending and infinity balance and I want the option to turn off that part.

**Comment by MrLoLf** [comment]
I am right now on my Holliday, but when I'm back I will start working on it. This feature should be very easy to implement (I hope so). So in two weeks when I'm back I can start working on this feature request. 

Thanks for this request and for your effort for making this request.

Fabian Roscher

**Comment by MrLoLf** [comment]
To give you a little update, I have added a config, but if you have a different config for the client and the server it causes some issues, when having it disabled, but on the client enabled and the other way round. If you want to still use it, you can check out the dev branch and compile it yourself. If you have it only installed on the server, there should be no issues. I won't publish this yet because of obvious reasons. If someone knows how to synch the server config with the client, I would appreciate the help.

**Comment by Roadhog360** [comment]
It is not practical to do so. Most mods just assume that the server and client have the same configuration, or else you can't join due to registry mismatches. This is normal and you shouldn't try to change it.

But if you wanted to, you could have the server send the packets to clients that login, telling them what the server chose for its configuration. I do not recommend this.

**Comment by chitinlink** [comment]
Shouldn't the server be the authority on what is allowed or not?

**Comment by Roadhog360** [comment]
That is correct, and if the client has a different configuration, then it either doesn't let it join due to registry mismatches, or correct the client's behavior by itself.

For example, if you disabled the Infinity arrows, the server would still let you fire the bow without an arrow, although it would be buggy. And if you turned on the option to make infinity and mending mutually exclusive again, the server would still not allow you to put them together, if the server had it off. Sometimes there might be a slight desync, but the client cannot create items the server doesn't want. That is simply not how multiplayer works.

**Comment by MrLoLf** [comment]
Do you know any mod I can look up that does this kind of things, synching or blocking players from joining entirely?

**Comment by Roadhog360** [comment]
No mods I know of currently sync configs. Mods typically are not programmed to prevent people from joining, the game is. The game will tell you "Fatally missing registey entries" or something along those lines if you try to join a server eith content you don't have or is not present.

**Comment by MrLoLf** [comment]
I have split the mod in two separate parts, one for just the infinity fix and one for adding infinity and mending together, you can find the new mod on [Modrinth](https://modrinth.com/mod/infinity-and-mending) and on [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/infinity-and-mending). Update the [infinity fix ](https://www.curseforge.com/minecraft/mc-mods/infinty-fix-fabric) mod to its newest version. I will push the commit on GitHub in the next days and the version for 1.18 I hope my new project gets reviewed fast, so you can start using it.
